%capacitor_2d.m The parallel plate capacitor problem
%
% Author: Chloros2 <chloros2@gmx.de>
% Created: 2018-05-13
%
% Copyright (C) 2018 Chloros2 <chloros2@gmx.de>
%
% This program is free software: you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see
% <https://www.gnu.org/licenses/>.
%

clear all;

addpath('ffmatlib');

%Reads a FreeFem++ mesh created with the savemesh(Th,"mesh.msh"); command
[p,b,t,nv,nbe,nt,labels]=ffreadmesh('capacitorp1.msh');
%Reads the PDE data
[u]=ffreaddata('capacitor_potential_p1only.txt');
[Ex,Ey]=ffreaddata('capacitor_field_p1only.txt');

%%%%%% Show Labels

figure;

handles=ffdraft(p,b,t, ...
                  'Mesh','off', ...
                  'Boundary','on', ...
                  'Title','Boundary / Edges Tests');
                  
figure;

handles=ffdraft(p,b,t, ...
                  'Mesh','off', ...
                  'Boundary','on', ...
                  'BDLabels',[3,4,5], ...
                  'BDShowText','on', ...
                  'Title','Boundary / Edges Tests');

figure;
                  
handles=ffdraft(p,b,t, ...
                  'Mesh','off', ...
                  'Boundary','on', ...
                  'BDLabels',[3,4,5], ...
                  'BDColors',['r','g','b'], ...
                  'BDShowText','on', ...
                  'Title','Boundary / Edges Tests');
                  

figure;
                  
handles=ffdraft(p,b,t, ...
                  'Mesh','off', ...
                  'Boundary','on', ...
                  'BDLabels',[3,4,5], ...
                  'BDColors','b', ...
                  'BDShowText','on', ...
                  'Title','Boundary / Edges Tests');

figure;

handles=ffdraft(p,b,t, ...
                  'Mesh','off', ...
                  'Boundary','on', ...
                  'BDColors','b', ...
                  'Title','Boundary / Edges Tests');
                  
figure;
                  
handles=ffdraft(p,b,t, ...
                  'Mesh','off', ...
                  'Boundary','on', ...
                  'BDLabels',[3,4], ...
                  'BDColors','g', ...
                  'BDShowText','on', ...
                  'Title','Boundary / Edges Tests');